// Sport names in the app's languages (the app's SportCatalog and Localizable.xcstrings), for the
// "<sport> session" a push names when a session has no title. Generated from the app; keep in sync.
import type { Language } from "./texts.ts";

export const sportNames: Record<string, Record<Language, string>> = {
  running: { en: "Running", fr: "Running", es: "Running", de: "Laufen", it: "Corsa", pt: "Corrida", nl: "Hardlopen" },
  trail: { en: "Trail", fr: "Trail", es: "Trail", de: "Trail", it: "Trail", pt: "Trail", nl: "Trail" },
  walking: {
    en: "Walking",
    fr: "Marche",
    es: "Caminar",
    de: "Walking",
    it: "Camminata",
    pt: "Caminhada",
    nl: "Wandelen",
  },
  hiking: {
    en: "Hiking",
    fr: "Randonnée",
    es: "Senderismo",
    de: "Wandern",
    it: "Escursionismo",
    pt: "Trilhos",
    nl: "Hiken",
  },
  cycling: {
    en: "Cycling",
    fr: "Vélo",
    es: "Ciclismo",
    de: "Radfahren",
    it: "Ciclismo",
    pt: "Ciclismo",
    nl: "Wielrennen",
  },
  spinning: {
    en: "Indoor cycling",
    fr: "Vélo en salle",
    es: "Ciclo indoor",
    de: "Indoor Cycling",
    it: "Indoor cycling",
    pt: "Ciclismo indoor",
    nl: "Indoor cycling",
  },
  mountainBiking: {
    en: "Mountain biking",
    fr: "VTT",
    es: "BTT",
    de: "Mountainbiken",
    it: "Mountain bike",
    pt: "BTT",
    nl: "Mountainbiken",
  },
  swimming: {
    en: "Swimming",
    fr: "Natation",
    es: "Natación",
    de: "Schwimmen",
    it: "Nuoto",
    pt: "Natação",
    nl: "Zwemmen",
  },
  openWater: {
    en: "Open water",
    fr: "Eau libre",
    es: "Aguas abiertas",
    de: "Freiwasser",
    it: "Acque libere",
    pt: "Águas abertas",
    nl: "Openwater",
  },
  triathlon: {
    en: "Triathlon",
    fr: "Triathlon",
    es: "Triatlón",
    de: "Triathlon",
    it: "Triathlon",
    pt: "Triatlo",
    nl: "Triatlon",
  },
  rowing: { en: "Rowing", fr: "Aviron", es: "Remo", de: "Rudern", it: "Canottaggio", pt: "Remo", nl: "Roeien" },
  surfing: { en: "Surfing", fr: "Surf", es: "Surf", de: "Surfen", it: "Surf", pt: "Surf", nl: "Surfen" },
  sailing: { en: "Sailing", fr: "Voile", es: "Vela", de: "Segeln", it: "Vela", pt: "Vela", nl: "Zeilen" },
  skateboarding: {
    en: "Skateboarding",
    fr: "Skate",
    es: "Skate",
    de: "Skateboarden",
    it: "Skateboard",
    pt: "Skate",
    nl: "Skateboarden",
  },
  skiing: { en: "Skiing", fr: "Ski", es: "Esquí", de: "Skifahren", it: "Sci", pt: "Esqui", nl: "Skiën" },
  crossCountrySki: {
    en: "Cross-country skiing",
    fr: "Ski de fond",
    es: "Esquí de fondo",
    de: "Langlauf",
    it: "Sci di fondo",
    pt: "Esqui de fundo",
    nl: "Langlaufen",
  },
  snowboarding: {
    en: "Snowboarding",
    fr: "Snowboard",
    es: "Snowboard",
    de: "Snowboarden",
    it: "Snowboard",
    pt: "Snowboard",
    nl: "Snowboarden",
  },
  strength: {
    en: "Strength",
    fr: "Musculation",
    es: "Fuerza",
    de: "Krafttraining",
    it: "Pesi",
    pt: "Musculação",
    nl: "Krachttraining",
  },
  functional: {
    en: "Functional training",
    fr: "Training fonctionnel",
    es: "Entrenamiento funcional",
    de: "Functional Training",
    it: "Allenamento funzionale",
    pt: "Treino funcional",
    nl: "Functional training",
  },
  crossfit: {
    en: "CrossFit",
    fr: "CrossFit",
    es: "CrossFit",
    de: "CrossFit",
    it: "CrossFit",
    pt: "CrossFit",
    nl: "CrossFit",
  },
  hiit: { en: "HIIT", fr: "HIIT", es: "HIIT", de: "HIIT", it: "HIIT", pt: "HIIT", nl: "HIIT" },
  calisthenics: {
    en: "Calisthenics",
    fr: "Calisthenics",
    es: "Calistenia",
    de: "Calisthenics",
    it: "Calisthenics",
    pt: "Calistenia",
    nl: "Calisthenics",
  },
  jumpRope: {
    en: "Jump rope",
    fr: "Corde à sauter",
    es: "Comba",
    de: "Seilspringen",
    it: "Salto con la corda",
    pt: "Saltar à corda",
    nl: "Touwtjespringen",
  },
  yoga: { en: "Yoga", fr: "Yoga", es: "Yoga", de: "Yoga", it: "Yoga", pt: "Ioga", nl: "Yoga" },
  pilates: { en: "Pilates", fr: "Pilates", es: "Pilates", de: "Pilates", it: "Pilates", pt: "Pilates", nl: "Pilates" },
  barre: { en: "Barre", fr: "Barre", es: "Barre", de: "Barre", it: "Barre", pt: "Barre", nl: "Barre" },
  mobility: {
    en: "Mobility",
    fr: "Mobilité",
    es: "Movilidad",
    de: "Mobility",
    it: "Mobilità",
    pt: "Mobilidade",
    nl: "Mobility",
  },
  taichi: { en: "Tai chi", fr: "Tai-chi", es: "Taichí", de: "Tai-Chi", it: "Tai chi", pt: "Tai chi", nl: "Tai chi" },
  dance: { en: "Dance", fr: "Danse", es: "Baile", de: "Tanzen", it: "Danza", pt: "Dança", nl: "Dansen" },
  gymnastics: {
    en: "Gymnastics",
    fr: "Gymnastique",
    es: "Gimnasia",
    de: "Turnen",
    it: "Ginnastica",
    pt: "Ginástica",
    nl: "Turnen",
  },
  boxing: { en: "Boxing", fr: "Boxe", es: "Boxeo", de: "Boxen", it: "Boxe", pt: "Boxe", nl: "Boksen" },
  kickboxing: {
    en: "Kickboxing",
    fr: "Kickboxing",
    es: "Kickboxing",
    de: "Kickboxen",
    it: "Kickboxing",
    pt: "Kickboxing",
    nl: "Kickboksen",
  },
  martialArts: {
    en: "Martial arts",
    fr: "Arts martiaux",
    es: "Artes marciales",
    de: "Kampfsport",
    it: "Arti marziali",
    pt: "Artes marciais",
    nl: "Vechtsport",
  },
  fencing: { en: "Fencing", fr: "Escrime", es: "Esgrima", de: "Fechten", it: "Scherma", pt: "Esgrima", nl: "Schermen" },
  padel: { en: "Padel", fr: "Padel", es: "Pádel", de: "Padel", it: "Padel", pt: "Padel", nl: "Padel" },
  tennis: { en: "Tennis", fr: "Tennis", es: "Tenis", de: "Tennis", it: "Tennis", pt: "Ténis", nl: "Tennis" },
  badminton: {
    en: "Badminton",
    fr: "Badminton",
    es: "Bádminton",
    de: "Badminton",
    it: "Badminton",
    pt: "Badminton",
    nl: "Badminton",
  },
  squash: { en: "Squash", fr: "Squash", es: "Squash", de: "Squash", it: "Squash", pt: "Squash", nl: "Squash" },
  tableTennis: {
    en: "Table tennis",
    fr: "Tennis de table",
    es: "Tenis de mesa",
    de: "Tischtennis",
    it: "Ping pong",
    pt: "Ténis de mesa",
    nl: "Tafeltennis",
  },
  pickleball: {
    en: "Pickleball",
    fr: "Pickleball",
    es: "Pickleball",
    de: "Pickleball",
    it: "Pickleball",
    pt: "Pickleball",
    nl: "Pickleball",
  },
  football: { en: "Football", fr: "Football", es: "Fútbol", de: "Fußball", it: "Calcio", pt: "Futebol", nl: "Voetbal" },
  basketball: {
    en: "Basketball",
    fr: "Basket",
    es: "Baloncesto",
    de: "Basketball",
    it: "Basket",
    pt: "Basquetebol",
    nl: "Basketbal",
  },
  volleyball: {
    en: "Volleyball",
    fr: "Volley",
    es: "Voleibol",
    de: "Volleyball",
    it: "Pallavolo",
    pt: "Voleibol",
    nl: "Volleybal",
  },
  rugby: { en: "Rugby", fr: "Rugby", es: "Rugby", de: "Rugby", it: "Rugby", pt: "Râguebi", nl: "Rugby" },
  handball: {
    en: "Handball",
    fr: "Handball",
    es: "Balonmano",
    de: "Handball",
    it: "Pallamano",
    pt: "Andebol",
    nl: "Handbal",
  },
  hockey: { en: "Hockey", fr: "Hockey", es: "Hockey", de: "Hockey", it: "Hockey", pt: "Hóquei", nl: "Hockey" },
  climbing: {
    en: "Climbing",
    fr: "Escalade",
    es: "Escalada",
    de: "Klettern",
    it: "Arrampicata",
    pt: "Escalada",
    nl: "Klimmen",
  },
  golf: { en: "Golf", fr: "Golf", es: "Golf", de: "Golf", it: "Golf", pt: "Golfe", nl: "Golf" },
  equestrian: {
    en: "Horse riding",
    fr: "Équitation",
    es: "Equitación",
    de: "Reiten",
    it: "Equitazione",
    pt: "Equitação",
    nl: "Paardrijden",
  },
  archery: {
    en: "Archery",
    fr: "Tir à l'arc",
    es: "Tiro con arco",
    de: "Bogenschießen",
    it: "Tiro con l'arco",
    pt: "Tiro com arco",
    nl: "Handboogschieten",
  },
  hyrox: { en: "Hyrox", fr: "Hyrox", es: "Hyrox", de: "Hyrox", it: "Hyrox", pt: "Hyrox", nl: "Hyrox" },
  runClub: {
    en: "Run club",
    fr: "Run club",
    es: "Club de running",
    de: "Laufgruppe",
    it: "Run club",
    pt: "Clube de corrida",
    nl: "Runclub",
  },
  ultra: {
    en: "Ultra running",
    fr: "Ultra-trail",
    es: "Ultra trail",
    de: "Ultralauf",
    it: "Ultra running",
    pt: "Ultra trail",
    nl: "Ultralopen",
  },
  gravel: { en: "Gravel", fr: "Gravel", es: "Gravel", de: "Gravel", it: "Gravel", pt: "Gravel", nl: "Gravel" },
  obstacleRace: {
    en: "Obstacle racing",
    fr: "Course à obstacles",
    es: "Carreras de obstáculos",
    de: "Hindernislauf",
    it: "Obstacle race",
    pt: "Corrida de obstáculos",
    nl: "Obstakelrun",
  },
  stairClimbing: {
    en: "Stair climbing",
    fr: "Montée d'escaliers",
    es: "Subir escaleras",
    de: "Treppenlaufen",
    it: "Salita di scale",
    pt: "Subir escadas",
    nl: "Traplopen",
  },
  kitesurf: {
    en: "Kitesurf",
    fr: "Kitesurf",
    es: "Kitesurf",
    de: "Kitesurfen",
    it: "Kitesurf",
    pt: "Kitesurf",
    nl: "Kitesurfen",
  },
  wingFoil: {
    en: "Wing foil",
    fr: "Wing foil",
    es: "Wing foil",
    de: "Wingfoil",
    it: "Wing foil",
    pt: "Wing foil",
    nl: "Wingfoil",
  },
  paddleBoard: {
    en: "Paddleboard",
    fr: "Paddle",
    es: "Paddle surf",
    de: "Stand-up-Paddling",
    it: "Paddleboard",
    pt: "Paddle surf",
    nl: "Suppen",
  },
  kayak: { en: "Kayak", fr: "Kayak", es: "Kayak", de: "Kajak", it: "Kayak", pt: "Caiaque", nl: "Kajak" },
  skiTouring: {
    en: "Ski touring",
    fr: "Ski de rando",
    es: "Esquí de travesía",
    de: "Skitouren",
    it: "Scialpinismo",
    pt: "Esqui de travessia",
    nl: "Toerskiën",
  },
  iceSkating: {
    en: "Ice skating",
    fr: "Patin à glace",
    es: "Patinaje sobre hielo",
    de: "Eislaufen",
    it: "Pattinaggio",
    pt: "Patinagem no gelo",
    nl: "Schaatsen",
  },
  parkour: { en: "Parkour", fr: "Parkour", es: "Parkour", de: "Parkour", it: "Parkour", pt: "Parkour", nl: "Parkour" },
  hotYoga: {
    en: "Hot yoga",
    fr: "Hot yoga",
    es: "Hot yoga",
    de: "Hot Yoga",
    it: "Hot yoga",
    pt: "Hot yoga",
    nl: "Hot yoga",
  },
  reformer: {
    en: "Reformer Pilates",
    fr: "Pilates Reformer",
    es: "Pilates reformer",
    de: "Reformer Pilates",
    it: "Pilates reformer",
    pt: "Pilates Reformer",
    nl: "Reformer pilates",
  },
  bjj: {
    en: "Jiu-jitsu",
    fr: "Jiu-jitsu",
    es: "Jiu-jitsu",
    de: "Jiu-Jitsu",
    it: "Jiu-jitsu",
    pt: "Jiu-jitsu",
    nl: "Jiujitsu",
  },
  beachTennis: {
    en: "Beach tennis",
    fr: "Beach tennis",
    es: "Beach tennis",
    de: "Beachtennis",
    it: "Beach tennis",
    pt: "Ténis de praia",
    nl: "Beachtennis",
  },
  beachVolley: {
    en: "Beach volley",
    fr: "Beach-volley",
    es: "Vóley playa",
    de: "Beachvolleyball",
    it: "Beach volley",
    pt: "Voleibol de praia",
    nl: "Beachvolleybal",
  },
  ultimate: {
    en: "Ultimate frisbee",
    fr: "Ultimate",
    es: "Ultimate frisbee",
    de: "Ultimate Frisbee",
    it: "Ultimate frisbee",
    pt: "Ultimate frisbee",
    nl: "Ultimate frisbee",
  },
  spikeball: {
    en: "Spikeball",
    fr: "Spikeball",
    es: "Spikeball",
    de: "Spikeball",
    it: "Spikeball",
    pt: "Spikeball",
    nl: "Spikeball",
  },
  bouldering: {
    en: "Bouldering",
    fr: "Bloc",
    es: "Boulder",
    de: "Bouldern",
    it: "Bouldering",
    pt: "Bouldering",
    nl: "Boulderen",
  },
};
