// The demo people of scripts/demo-profiles.ts. Written by hand so every profile reads like a real one:
// sports that go together, a bio that matches them, places around Lyon. Prompt questions are the app's
// library text (English, ProfilePrompt.library in drafft-ios), answers are French like the rest.
// Lifestyle answers are the app's English option values (LifestylePicker), "" when left unanswered.

export type Gender = "woman" | "man" | "nonbinary";
export type Icebreaker =
  | { kind: "twoTruths"; statements: string[]; lieIndex: number }
  | { kind: "joke"; setup: string; punchline: string }
  | { kind: "hotTake"; text: string }
  | { kind: "thisOrThat"; question: string; options: string[]; pick: number }
  | { kind: "guess"; question: string; options: string[]; answer: number };

export interface Persona {
  name: string;
  gender: Gender;
  age: number;
  /** Genders they want to see; empty = everyone. */
  interestedIn: Gender[];
  /** [sport id, sessions per week], most important first. */
  sports: [string, number][];
  bio: string;
  goal: string;
  spot: string;
  /** [chronotype, diet, drinks, smokes] */
  lifestyle: [string, string, string, string];
  prompts: [string, string][];
  icebreaker?: Icebreaker;
}

const W: Gender = "woman", M: Gender = "man", N: Gender = "nonbinary";

export const personas: Persona[] = [
  {
    name: "Camille",
    gender: W,
    age: 29,
    interestedIn: [M],
    sports: [["running", 4], ["yoga", 2]],
    bio:
      "Kiné le jour, coureuse le matin avant que la ville se réveille. Je cherche quelqu'un pour les sorties longues du dimanche et le café qui suit.",
    goal: "Passer sous les 1h45 au semi de Lyon",
    spot: "Les quais du Rhône au lever du soleil",
    lifestyle: ["Very early bird", "Flexitarian", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "18 km tranquilles le long du Rhône, puis brunch à la Guillotière.",
    ], [
      "The way to win me over",
      "Me proposer un fractionné sous la pluie sans râler.",
    ]],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai couru un marathon déguisée en banane",
        "Je n'ai jamais vu la mer avant 20 ans",
        "Je connais tous les escaliers de la Croix-Rousse",
      ],
      lieIndex: 1,
    },
  },
  {
    name: "Thomas",
    gender: M,
    age: 32,
    interestedIn: [W],
    sports: [["climbing", 3], ["bouldering", 2], ["hiking", 1]],
    bio:
      "Ingénieur à la Part-Dieu, grimpeur partout ailleurs. Le week-end je file dans le Vercors dès qu'il fait beau.",
    goal: "Enchaîner mon premier 7a en falaise",
    spot: "La salle de bloc à Gerland",
    lifestyle: ["Early bird", "Omnivore", "Post-race only", "Never"],
    prompts: [[
      "Green flag in a training partner",
      "Quelqu'un qui vérifie mon nœud sans que je demande.",
    ], [
      "After a workout you'll find me",
      "Mains pleines de magnésie, en train de commander une pizza.",
    ]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Bloc ou voie ?",
      options: ["Bloc", "Voie"],
      pick: 1,
    },
  },
  {
    name: "Léa",
    gender: W,
    age: 26,
    interestedIn: [M, W],
    sports: [["padel", 3], ["tennis", 1]],
    bio:
      "Je joue au padel trois fois par semaine et je cherche encore le partenaire qui ne me laisse pas tous les smashs.",
    goal: "Monter en P250 avant l'été",
    spot: "Les terrains de padel de Villeurbanne",
    lifestyle: ["Night owl", "Omnivore", "Apéro is sacred", "Never"],
    prompts: [["My competitive streak, rated", "11 sur 10. Même au Uno."], [
      "A first date that isn't dinner",
      "Un double mixte, perdant paie la tournée.",
    ]],
    icebreaker: {
      kind: "hotTake",
      text: "Le padel, c'est mieux que le tennis. Je ne débattrai pas.",
    },
  },
  {
    name: "Hugo",
    gender: M,
    age: 28,
    interestedIn: [W],
    sports: [["cycling", 4], ["gravel", 2]],
    bio:
      "Vélo tous les jours pour aller bosser, et le samedi dans les Monts d'Or. J'aime les cols, les cartes IGN et les pauses boulangerie.",
    goal: "Monter le Ventoux par les trois faces",
    spot: "Le col de la Croix-Rousse, à fond",
    lifestyle: ["Early bird", "Meat lover", "Socially", "Never"],
    prompts: [[
      "The piece of gear I'd save in a fire",
      "Mon vélo. Puis mon chat. Puis le reste.",
    ], [
      "The snack that fuels my entire personality",
      "Le chausson aux pommes de la boulangerie de Limonest.",
    ]],
  },
  {
    name: "Manon",
    gender: W,
    age: 31,
    interestedIn: [M],
    sports: [["trail", 3], ["running", 2], ["hiking", 1]],
    bio:
      "Trail dans les Monts d'Or, randonnée dans le Pilat, et beaucoup de fromage entre les deux. Je travaille dans l'édition.",
    goal: "Finir la SaintéLyon en solo",
    spot: "Le Mont Verdun",
    lifestyle: ["Early bird", "Vegetarian", "Rarely", "Never"],
    prompts: [[
      "A goal that scares me a little",
      "Mon premier 80 km. J'y pense tous les soirs.",
    ], [
      "I'll know it's a match if",
      "Tu ne fais pas la tête quand il pleut au départ.",
    ]],
    icebreaker: {
      kind: "guess",
      question: "Combien de paires de chaussures de trail j'ai ?",
      options: ["2", "5", "9"],
      answer: 2,
    },
  },
  {
    name: "Nathan",
    gender: M,
    age: 25,
    interestedIn: [W],
    sports: [["football", 2], ["strength", 3]],
    bio:
      "Foot à cinq le mardi, muscu le reste du temps. Étudiant en master à Lyon 3, fan de l'OL même les mauvaises saisons.",
    goal: "Tenir 100 kg au développé couché",
    spot: "Le parc de Gerland",
    lifestyle: ["Night owl", "Meat lover", "Socially", "Never"],
    prompts: [[
      "I'd drop everything to watch",
      "Un OL Saint-Étienne, évidemment.",
    ], ["My most controversial opinion", "Le jour des jambes est surcoté."]],
    icebreaker: {
      kind: "joke",
      setup: "Pourquoi les footballeurs sont nuls en cuisine ?",
      punchline: "Parce qu'ils ratent toujours les passes.",
    },
  },
  {
    name: "Chloé",
    gender: W,
    age: 27,
    interestedIn: [M],
    sports: [["yoga", 4], ["pilates", 2]],
    bio:
      "Prof de yoga à la Croix-Rousse. Je crois aux matins lents, aux salutations au soleil et aux tartines au miel.",
    goal: "Tenir l'équilibre sur les mains au milieu du salon",
    spot: "Le Jardin des Chartreux",
    lifestyle: ["Very early bird", "Vegan", "Never", "Never"],
    prompts: [[
      "I feel most like myself when",
      "Je suis sur mon tapis avant que la ville se réveille.",
    ], ["You should not go out with me if", "Tu détestes le thé."]],
  },
  {
    name: "Maxime",
    gender: M,
    age: 34,
    interestedIn: [W],
    sports: [["triathlon", 4], ["swimming", 3], ["cycling", 2]],
    bio:
      "Je me lève à 5h30 pour nager, et j'assume. Trois disciplines, une seule obsession : finir un Ironman sans marcher.",
    goal: "Ironman de Nice l'an prochain",
    spot: "Le bassin du Centre nautique Tony Bertrand",
    lifestyle: ["Very early bird", "Omnivore", "Post-race only", "Never"],
    prompts: [["A stat I'm weirdly proud of", "Ma FC au repos : 42."], [
      "My pre-race ritual involves",
      "Des pâtes, toujours les mêmes, et un épisode de Kaamelott.",
    ]],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai déjà nagé dans le lac d'Annecy en décembre",
        "J'ai peur des pigeons",
        "J'ai un vélo qui vaut plus cher que ma voiture",
      ],
      lieIndex: 0,
    },
  },
  {
    name: "Inès",
    gender: W,
    age: 24,
    interestedIn: [M],
    sports: [["dance", 3], ["hiit", 2]],
    bio:
      "Danseuse amatrice, étudiante en archi. Je cherche quelqu'un qui ose danser en soirée sans se cacher derrière le bar.",
    goal: "Monter un spectacle avec ma troupe",
    spot: "Les berges du Rhône le soir",
    lifestyle: ["Night owl", "Flexitarian", "Socially", "Sometimes"],
    prompts: [["Karaoke song, no hesitation", "Alors on danse, de Stromae."], [
      "My love language is basically",
      "Une playlist faite pour moi.",
    ]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Salsa ou hip-hop ?",
      options: ["Salsa", "Hip-hop"],
      pick: 1,
    },
  },
  {
    name: "Lucas",
    gender: M,
    age: 30,
    interestedIn: [W],
    sports: [["running", 3], ["runClub", 1], ["strength", 2]],
    bio:
      "Développeur, coureur du jeudi soir avec mon run club. Je fais aussi les meilleures crêpes du 7e, demande autour de toi.",
    goal: "Marathon de Paris en moins de 3h30",
    spot: "Le parc de la Tête d'Or",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "Rest day? Here's what that really means",
      "Une sortie à vélo. Tranquille. Enfin presque.",
    ], [
      "Together we could finally",
      "Courir le tour du parc sans parler de boulot.",
    ]],
  },
  {
    name: "Sarah",
    gender: W,
    age: 33,
    interestedIn: [M],
    sports: [["swimming", 3], ["openWater", 1], ["yoga", 1]],
    bio: "Pédiatre, nageuse depuis l'enfance. L'été je nage dans les lacs, l'hiver je compte les longueurs.",
    goal: "Traverser le lac d'Annecy à la nage",
    spot: "Le lac du Grand Parc de Miribel",
    lifestyle: ["Early bird", "Pescatarian", "Rarely", "Never"],
    prompts: [[
      "What keeps me going on hard days",
      "La sensation de l'eau froide le matin.",
    ], ["I'm looking for someone who", "Rit fort et n'a pas peur des lacs."]],
    icebreaker: {
      kind: "hotTake",
      text: "La piscine à 7h du matin, c'est le meilleur moment de la journée.",
    },
  },
  {
    name: "Antoine",
    gender: M,
    age: 36,
    interestedIn: [W],
    sports: [["mountainBiking", 3], ["skiing", 1], ["trail", 1]],
    bio:
      "Papa d'un golden retriever, VTT dans les Monts du Lyonnais et ski dès que la neige tombe. Je bosse dans l'énergie.",
    goal: "Faire la Transvésubienne",
    spot: "Les singles du Mont Thou",
    lifestyle: ["Early bird", "Meat lover", "Socially", "Never"],
    prompts: [[
      "The dumbest injury I've ever had",
      "Entorse du poignet en descendant du canapé.",
    ], [
      "A first date that isn't dinner",
      "Une balade avec le chien, et une glace après.",
    ]],
  },
  {
    name: "Juliette",
    gender: W,
    age: 28,
    interestedIn: [],
    sports: [["bouldering", 3], ["yoga", 1]],
    bio:
      "Bloc trois fois par semaine, illustratrice le reste du temps. Mes avant-bras sont plus forts que mes arguments.",
    goal: "Sortir un bloc violet sans tricher",
    spot: "Le Mur de Lyon",
    lifestyle: ["Night owl", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "My hidden talent nobody believes",
      "Je dessine les gens en trente secondes.",
    ], [
      "Green flag in a training partner",
      "Il te pare même sur les blocs faciles.",
    ]],
    icebreaker: {
      kind: "guess",
      question: "Mon bloc préféré ?",
      options: ["Les dévers", "Les dalles", "Les toits"],
      answer: 0,
    },
  },
  {
    name: "Romain",
    gender: M,
    age: 29,
    interestedIn: [W],
    sports: [["crossfit", 4], ["hyrox", 1]],
    bio: "Coach dans une box à Villeurbanne. Je promets de ne pas te parler de macros au premier rendez-vous.",
    goal: "Podium Hyrox en double",
    spot: "Ma box, évidemment",
    lifestyle: ["Very early bird", "Meat lover", "Rarely", "Never"],
    prompts: [[
      "My most controversial opinion",
      "Les burpees, c'est agréable. Si, si.",
    ], [
      "After a workout you'll find me",
      "Allongé par terre, à fixer le plafond.",
    ]],
    icebreaker: {
      kind: "joke",
      setup: "Combien de crossfitters pour changer une ampoule ?",
      punchline: "Un seul, mais il va le poster partout.",
    },
  },
  {
    name: "Alice",
    gender: W,
    age: 35,
    interestedIn: [M],
    sports: [["hiking", 2], ["skiTouring", 1], ["running", 2]],
    bio: "Avocate, montagnarde. Je passe mes week-ends en altitude et mes soirées à préparer les suivants.",
    goal: "Le Mont Blanc l'été prochain",
    spot: "Le sentier des crêtes du Pilat",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "Départ à 5h, sommet à 10h, tartiflette à 13h.",
    ], [
      "The person who got me into sport",
      "Mon grand-père, guide à Chamonix.",
    ]],
  },
  {
    name: "Mehdi",
    gender: M,
    age: 27,
    interestedIn: [W],
    sports: [["boxing", 3], ["running", 2]],
    bio: "Boxe anglaise depuis dix ans, infirmier de nuit. Calme dehors, un peu moins sur le ring.",
    goal: "Mon premier combat amateur",
    spot: "Le club de boxe de la Guillotière",
    lifestyle: ["Night owl", "Omnivore", "Never", "Never"],
    prompts: [[
      "The best advice a coach ever gave me",
      "Respire. Toujours. Même quand ça cogne.",
    ], ["You should not go out with me if", "Tu as peur des films d'horreur."]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Corde à sauter ou sac de frappe ?",
      options: ["Corde à sauter", "Sac de frappe"],
      pick: 1,
    },
  },
  {
    name: "Emma",
    gender: W,
    age: 23,
    interestedIn: [M],
    sports: [["volleyball", 2], ["beachVolley", 2]],
    bio:
      "Étudiante en STAPS, volley en salle l'hiver, beach l'été à Miribel. Toujours partante pour un match improvisé.",
    goal: "Le championnat universitaire avec mon équipe",
    spot: "Les terrains de beach de Miribel",
    lifestyle: ["Night owl", "Omnivore", "Apéro is sacred", "Never"],
    prompts: [[
      "I will never shut up about",
      "Le beach volley. Pardon d'avance.",
    ], [
      "Two truths and a lie about my fitness",
      "Je saute plus haut que toi, je cours vite, j'aime le cardio.",
    ]],
  },
  {
    name: "Julien",
    gender: M,
    age: 38,
    interestedIn: [W],
    sports: [["golf", 2], ["tennis", 2], ["walking", 3]],
    bio: "Architecte, golfeur du dimanche et joueur de tennis du mercredi. J'aime les gens qui prennent leur temps.",
    goal: "Descendre à 12 de handicap",
    spot: "Le golf de Lyon-Villette d'Anthon",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "A first date that isn't dinner",
      "Un practice et un verre au club-house.",
    ], [
      "I feel most like myself when",
      "Je marche dans le Vieux Lyon un dimanche matin.",
    ]],
    icebreaker: {
      kind: "hotTake",
      text: "Le golf est un vrai sport. Viens porter mon sac, tu verras.",
    },
  },
  {
    name: "Clara",
    gender: W,
    age: 30,
    interestedIn: [M],
    sports: [["running", 3], ["cycling", 2], ["swimming", 1]],
    bio:
      "Je me suis mise au triathlon l'an dernier et je n'arrive plus à m'arrêter. Data analyst, donc oui, j'ai un tableur pour mes entraînements.",
    goal: "Le triathlon M de Lyon",
    spot: "La Confluence, côté Saône",
    lifestyle: ["Early bird", "Flexitarian", "Rarely", "Never"],
    prompts: [[
      "A stat I'm weirdly proud of",
      "312 jours d'entraînement consécutifs.",
    ], [
      "I'm looking for someone who",
      "Aime les tableurs autant que les sorties longues.",
    ]],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai un tableur pour mes courses",
        "J'ai déjà gagné une course sur 10 km",
        "Je ne sais pas faire de vélo sans les mains",
      ],
      lieIndex: 1,
    },
  },
  {
    name: "Paul",
    gender: M,
    age: 26,
    interestedIn: [W],
    sports: [["skateboarding", 3], ["surfing", 1]],
    bio:
      "Skate aux Terreaux, surf quand je peux descendre à Hossegor. Graphiste free-lance, toujours une planche sous le bras.",
    goal: "Passer un kickflip propre en ligne",
    spot: "Le skatepark de Gerland",
    lifestyle: ["Night owl", "Vegetarian", "Socially", "Sometimes"],
    prompts: [[
      "My playlist for the last kilometre",
      "Pas de kilomètre, que des rides. Et du rap lyonnais.",
    ], ["My most irrational fear", "Les escalators. Je n'explique pas."]],
  },
  {
    name: "Margaux",
    gender: W,
    age: 32,
    interestedIn: [M],
    sports: [["reformer", 2], ["barre", 2], ["running", 1]],
    bio:
      "Pilates reformer deux fois par semaine, un peu de course quand il fait beau. Je travaille dans la mode et je cuisine très mal.",
    goal: "Courir mes premiers 10 km",
    spot: "Le studio de pilates du 6e",
    lifestyle: ["Early bird", "Pescatarian", "Socially", "Never"],
    prompts: [[
      "The way to win me over",
      "Me cuisiner quelque chose. N'importe quoi, vraiment.",
    ], [
      "Something I'm training for outside of sport",
      "Arrêter de brûler les pâtes.",
    ]],
    icebreaker: {
      kind: "joke",
      setup: "Ma prof de pilates m'a dit de rentrer le ventre.",
      punchline: "J'ai répondu que je l'avais déjà fait, c'était ça le problème.",
    },
  },
  {
    name: "Alexandre",
    gender: M,
    age: 31,
    interestedIn: [W],
    sports: [["rugby", 2], ["strength", 2], ["running", 1]],
    bio: "Troisième ligne au LOU amateur, chef de projet en semaine. Grand gabarit, grand cœur, grand appétit.",
    goal: "Remonter en Fédérale 2 avec mon club",
    spot: "Le stade de Gerland",
    lifestyle: ["Early bird", "Meat lover", "Apéro is sacred", "Never"],
    prompts: [[
      "After a workout you'll find me",
      "À la troisième mi-temps, évidemment.",
    ], [
      "Green flag in a training partner",
      "Il te ramasse quand tu tombes, au sens propre.",
    ]],
  },
  {
    name: "Zoé",
    gender: W,
    age: 25,
    interestedIn: [M, N],
    sports: [["climbing", 2], ["hiking", 2], ["yoga", 1]],
    bio: "Je grimpe, je randonne, je fais du yoga pour réparer les deux. Étudiante en biologie, amoureuse des lichens.",
    goal: "Le GR20 en entier",
    spot: "Les falaises de Saint-Hilaire",
    lifestyle: ["Early bird", "Vegetarian", "Rarely", "Never"],
    prompts: [[
      "I will never shut up about",
      "Les lichens. Ils sont fascinants, je te jure.",
    ], ["Together we could finally", "Faire le tour du Mont Blanc."]],
    icebreaker: {
      kind: "guess",
      question: "Mon sommet préféré ?",
      options: [
        "Le Mont Aiguille",
        "Le Crêt de la Perdrix",
        "La Dent de Crolles",
      ],
      answer: 0,
    },
  },
  {
    name: "Victor",
    gender: M,
    age: 33,
    interestedIn: [W],
    sports: [["trail", 3], ["ultra", 1], ["hiking", 1]],
    bio: "Ultra-traileur, je cours la nuit avec une frontale et je dors peu. Je travaille dans une ONG.",
    goal: "La Diagonale des Fous",
    spot: "Les sentiers du Mont Cindre",
    lifestyle: ["Very early bird", "Omnivore", "Post-race only", "Never"],
    prompts: [[
      "The worst run of my life happened when",
      "Ma frontale m'a lâché à 3h du matin dans le Vercors.",
    ], ["What keeps me going on hard days", "Le prochain ravito."]],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai couru 160 km d'un coup",
        "Je n'ai jamais bu de café",
        "J'ai vu un loup en courant",
      ],
      lieIndex: 1,
    },
  },
  {
    name: "Jade",
    gender: W,
    age: 28,
    interestedIn: [M],
    sports: [["hiit", 3], ["strength", 2], ["running", 1]],
    bio: "Responsable marketing, accro au HIIT de 7h. J'ai une énergie de golden retriever, tu es prévenu.",
    goal: "Faire dix tractions d'affilée",
    spot: "Le parc Blandan",
    lifestyle: ["Very early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My love language is basically",
      "Me tenir la porte de la salle et me garder une barre.",
    ], [
      "Unpopular opinion about stretching",
      "Personne ne le fait vraiment, avouons-le.",
    ]],
  },
  {
    name: "Arthur",
    gender: M,
    age: 24,
    interestedIn: [W],
    sports: [["basketball", 3], ["running", 1]],
    bio:
      "Basket sur le playground de la Croix-Rousse tous les soirs d'été. Étudiant en école de commerce, moins sérieux qu'il n'y paraît.",
    goal: "Réussir un dunk avant mes 25 ans",
    spot: "Le playground du parc de la Cerisaie",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Never"],
    prompts: [[
      "I'd drop everything to watch",
      "Les finales NBA, même à 3h du matin.",
    ], ["My competitive streak, rated", "Je refais la partie jusqu'à gagner."]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Trois points ou dunk ?",
      options: ["Trois points", "Dunk"],
      pick: 0,
    },
  },
  {
    name: "Louise",
    gender: W,
    age: 37,
    interestedIn: [M],
    sports: [["walking", 4], ["yoga", 2], ["swimming", 1]],
    bio: "Psychologue, maman d'un ado qui me trouve ringarde. Je marche beaucoup, je nage un peu, je ris énormément.",
    goal: "Marcher de Lyon à Saint-Jacques",
    spot: "Les quais de Saône jusqu'à l'île Barbe",
    lifestyle: ["Early bird", "Flexitarian", "Socially", "Never"],
    prompts: [[
      "A first date that isn't dinner",
      "Une balade jusqu'à l'île Barbe, une glace sur le chemin.",
    ], [
      "I'll know it's a match if",
      "On parle deux heures sans voir le temps passer.",
    ]],
  },
  {
    name: "Gabriel",
    gender: M,
    age: 29,
    interestedIn: [W, M],
    sports: [["swimming", 3], ["running", 2], ["yoga", 1]],
    bio:
      "Nageur, coureur, et je commence le yoga pour mon dos. Je travaille dans le cinéma et je pleure devant tous les films.",
    goal: "Nager 5 km sans m'arrêter",
    spot: "La piscine du Rhône l'été",
    lifestyle: ["Early bird", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "My most irrational fear",
      "Les poissons dans les lacs. Oui, je nage quand même.",
    ], ["I'm looking for someone who", "Accepte que je pleure devant Pixar."]],
    icebreaker: {
      kind: "hotTake",
      text: "La piscine du Rhône est le meilleur endroit de Lyon en juillet.",
    },
  },
  {
    name: "Lina",
    gender: W,
    age: 26,
    interestedIn: [M],
    sports: [["kickboxing", 3], ["running", 1]],
    bio:
      "Kickboxing trois fois par semaine, comptable le reste du temps. Les chiffres et les coups de pied, même rigueur.",
    goal: "Ceinture noire d'ici deux ans",
    spot: "Le dojo de Monplaisir",
    lifestyle: ["Night owl", "Omnivore", "Rarely", "Never"],
    prompts: [[
      "My hidden talent nobody believes",
      "Je fais le grand écart. Facilement.",
    ], ["You should not go out with me if", "Tu triches au Monopoly."]],
  },
  {
    name: "Louis",
    gender: M,
    age: 35,
    interestedIn: [W],
    sports: [["cycling", 3], ["running", 2]],
    bio:
      "Médecin urgentiste, je décompresse sur le vélo. Les sorties du samedi dans le Beaujolais finissent souvent par une dégustation.",
    goal: "L'Étape du Tour",
    spot: "Les routes du Beaujolais",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "100 km dans le Beaujolais, puis un verre de Morgon.",
    ], ["The best advice a coach ever gave me", "Mange avant d'avoir faim."]],
    icebreaker: {
      kind: "guess",
      question: "Combien de km à vélo l'an dernier ?",
      options: ["3 000", "8 000", "12 000"],
      answer: 1,
    },
  },
  {
    name: "Charlotte",
    gender: W,
    age: 29,
    interestedIn: [M],
    sports: [["tennis", 3], ["padel", 1]],
    bio:
      "Tennis depuis mes 6 ans, je joue encore en championnat. Consultante, souvent en déplacement, toujours avec ma raquette.",
    goal: "Passer 15/1",
    spot: "Le TCL du parc de la Tête d'Or",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My competitive streak, rated",
      "Je dis que c'est pour le plaisir. C'est faux.",
    ], [
      "A first date that isn't dinner",
      "Un match, puis on parle du score toute la soirée.",
    ]],
  },
  {
    name: "Adam",
    gender: M,
    age: 27,
    interestedIn: [W],
    sports: [["calisthenics", 4], ["running", 1]],
    bio:
      "Street workout au parc de Gerland, développeur web en télétravail. Je peux tenir le drapeau humain, demande-moi.",
    goal: "Tenir un planche complet",
    spot: "Les barres du parc de Gerland",
    lifestyle: ["Early bird", "Omnivore", "Never", "Never"],
    prompts: [["A stat I'm weirdly proud of", "25 tractions d'affilée."], [
      "My most controversial opinion",
      "Pas besoin de salle, un parc suffit.",
    ]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Parc ou salle ?",
      options: ["Parc", "Salle"],
      pick: 0,
    },
  },
  {
    name: "Mila",
    gender: W,
    age: 22,
    interestedIn: [M],
    sports: [["dance", 2], ["yoga", 2]],
    bio: "Étudiante en lettres à Lyon 2, danse contemporaine et yoga. Je lis dans le métro et je souligne tout.",
    goal: "Tenir une posture de corbeau une minute",
    spot: "Le parc de la Tête d'Or près des serres",
    lifestyle: ["Night owl", "Vegetarian", "Rarely", "Never"],
    prompts: [["I will never shut up about", "Les romans d'Annie Ernaux."], [
      "My love language is basically",
      "Un livre offert avec un mot dedans.",
    ]],
  },
  {
    name: "Raphaël",
    gender: M,
    age: 30,
    interestedIn: [W],
    sports: [["padel", 3], ["running", 1], ["strength", 1]],
    bio: "Commercial, joueur de padel acharné. Je cherche une partenaire de jeu, et plus si affinités au deuxième set.",
    goal: "Gagner un tournoi P100",
    spot: "Le padel club de Vaulx",
    lifestyle: ["Night owl", "Omnivore", "Apéro is sacred", "Never"],
    prompts: [[
      "I'll know it's a match if",
      "Tu m'appelles au filet sans hésiter.",
    ], [
      "After a workout you'll find me",
      "En terrasse, le sac encore sur l'épaule.",
    ]],
    icebreaker: {
      kind: "joke",
      setup: "Quelle est la différence entre un joueur de padel et un vendeur de voitures ?",
      punchline: "Le vendeur de voitures sait quand se taire.",
    },
  },
  {
    name: "Anna",
    gender: W,
    age: 34,
    interestedIn: [M],
    sports: [["trail", 2], ["skiTouring", 2], ["climbing", 1]],
    bio:
      "Géologue, donc forcément montagnarde. Ski de rando l'hiver, trail l'été, et toujours une pierre dans la poche.",
    goal: "La Pierra Menta",
    spot: "Le Vercors, côté Corrençon",
    lifestyle: ["Very early bird", "Omnivore", "Rarely", "Never"],
    prompts: [[
      "I will never shut up about",
      "La formation des Alpes. Désolée d'avance.",
    ], [
      "My ideal Sunday session",
      "Peaux de phoque, lever du soleil, descente en poudreuse.",
    ]],
  },
  {
    name: "Jules",
    gender: M,
    age: 25,
    interestedIn: [W],
    sports: [["running", 3], ["football", 1]],
    bio: "Je cours pour pouvoir manger plus de pizza. Doctorant en physique, j'explique la relativité si tu insistes.",
    goal: "Le semi de Lyon en 1h30",
    spot: "Les quais du Rhône côté Guillotière",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Never"],
    prompts: [[
      "The snack that fuels my entire personality",
      "Une part de pizza froide le matin.",
    ], [
      "My hidden talent nobody believes",
      "Je résous un Rubik's cube en une minute.",
    ]],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai un doctorat presque fini",
        "J'ai couru un semi en pyjama",
        "Je n'ai jamais mangé d'ananas",
      ],
      lieIndex: 2,
    },
  },
  {
    name: "Élise",
    gender: W,
    age: 31,
    interestedIn: [M],
    sports: [["rowing", 3], ["running", 1]],
    bio:
      "Aviron sur la Saône à l'aube, ingénieure en environnement. J'aime les gens ponctuels et les levers de soleil.",
    goal: "Les championnats de France en double",
    spot: "Le club d'aviron de l'île Barbe",
    lifestyle: ["Very early bird", "Flexitarian", "Rarely", "Never"],
    prompts: [[
      "Green flag in a training partner",
      "Ponctuel à 6h, sans se plaindre.",
    ], [
      "I feel most like myself when",
      "Je glisse sur la Saône avant le lever du jour.",
    ]],
  },
  {
    name: "Théo",
    gender: M,
    age: 28,
    interestedIn: [W],
    sports: [["bouldering", 3], ["running", 1]],
    bio:
      "Bloc, café et vinyles. Je bosse dans une brasserie artisanale à la Croix-Rousse, donc oui, je peux te conseiller une bière.",
    goal: "Mon premier 7b en bloc",
    spot: "Arkose Lyon",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Never"],
    prompts: [[
      "After a workout you'll find me",
      "Derrière le comptoir, avec une IPA maison.",
    ], ["Karaoke song, no hesitation", "Mistral gagnant. Tout le bar chante."]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Café ou bière après la séance ?",
      options: ["Café", "Bière"],
      pick: 1,
    },
  },
  {
    name: "Rose",
    gender: W,
    age: 27,
    interestedIn: [W],
    sports: [["running", 3], ["yoga", 1]],
    bio:
      "Sage-femme, coureuse de fond. Je cherche une partenaire de course qui aime autant les sorties longues que les longues discussions.",
    goal: "Mon premier marathon",
    spot: "Le Grand Parc de Miribel",
    lifestyle: ["Early bird", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "25 km en papotant, puis un pain au chocolat.",
    ], [
      "The way to win me over",
      "Me proposer une sortie au lever du soleil.",
    ]],
  },
  {
    name: "Baptiste",
    gender: M,
    age: 32,
    interestedIn: [W],
    sports: [["kitesurf", 2], ["wingFoil", 1], ["running", 1]],
    bio:
      "Je check la météo du vent plus souvent que mes mails. Kite à Leucate dès que ça souffle, prof d'histoire le reste du temps.",
    goal: "Le saut à 10 mètres",
    spot: "Le lac de Miribel",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "I'd drop everything to watch",
      "Les prévisions de vent du week-end.",
    ], [
      "The dumbest injury I've ever had",
      "Coupé avec une feuille de papier en corrigeant des copies.",
    ]],
  },
  {
    name: "Lou",
    gender: N,
    age: 26,
    interestedIn: [],
    sports: [["climbing", 2], ["yoga", 2], ["cycling", 1]],
    bio:
      "Je grimpe, je pédale partout, je fais du yoga pour garder la tête calme. Je travaille dans une librairie de la Croix-Rousse.",
    goal: "Grimper en tête sans trembler",
    spot: "La salle Climb Up de Gerland",
    lifestyle: ["Night owl", "Vegan", "Rarely", "Never"],
    prompts: [[
      "I'm looking for someone who",
      "Aime les livres d'occasion et les sorties vélo sans but.",
    ], [
      "My hidden talent nobody believes",
      "Je recommande un livre à chacun en deux questions.",
    ]],
    icebreaker: {
      kind: "guess",
      question: "Combien de livres je lis par mois ?",
      options: ["2", "5", "10"],
      answer: 1,
    },
  },
  {
    name: "Pierre",
    gender: M,
    age: 40,
    interestedIn: [W],
    sports: [["running", 3], ["cycling", 2]],
    bio:
      "Divorcé, deux enfants un week-end sur deux, coureur tous les jours. Chef d'entreprise, mais j'éteins mon téléphone en courant.",
    goal: "Courir un marathon sur chaque continent",
    spot: "Le parc de Parilly",
    lifestyle: ["Very early bird", "Omnivore", "Socially", "Never"],
    prompts: [
      ["A stat I'm weirdly proud of", "Douze marathons, zéro abandon."],
      [
        "What keeps me going on hard days",
        "Mes enfants qui m'attendent à l'arrivée.",
      ],
    ],
  },
  {
    name: "Agathe",
    gender: W,
    age: 30,
    interestedIn: [M],
    sports: [["equestrian", 2], ["running", 2]],
    bio: "Équitation depuis toujours, vétérinaire pour chevaux. Je cours aussi, mais moins vite que mon cheval.",
    goal: "Mon premier concours de complet",
    spot: "Les chemins des Monts d'Or",
    lifestyle: ["Very early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "You should not go out with me if",
      "Tu es allergique aux chevaux. Ou aux chiens. Ou aux chats.",
    ], [
      "I feel most like myself when",
      "Je suis en selle, dans la brume du matin.",
    ]],
  },
  {
    name: "Samuel",
    gender: M,
    age: 27,
    interestedIn: [W],
    sports: [["handball", 2], ["strength", 2]],
    bio: "Handball en club depuis l'enfance, kiné en libéral. Je soigne les dos et je casse les miens le week-end.",
    goal: "Remonter en Nationale 3",
    spot: "Le gymnase de Villeurbanne",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "The dumbest injury I've ever had",
      "Doigt cassé en ouvrant un pot de cornichons.",
    ], ["Green flag in a training partner", "Il s'échauffe vraiment."]],
    icebreaker: {
      kind: "hotTake",
      text: "Le handball est le sport le plus sous-coté de France.",
    },
  },
  {
    name: "Nina",
    gender: W,
    age: 25,
    interestedIn: [M],
    sports: [["running", 2], ["hiit", 2], ["dance", 1]],
    bio:
      "Je viens de m'installer à Lyon pour mon premier job. Je cherche des gens pour courir, danser et découvrir les bouchons.",
    goal: "Courir les 10 km de Lyon",
    spot: "Les berges du Rhône",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Never"],
    prompts: [[
      "Together we could finally",
      "Tester tous les bouchons du Vieux Lyon.",
    ], [
      "A first date that isn't dinner",
      "Une course au parc, puis un verre en terrasse.",
    ]],
  },
  {
    name: "Mathis",
    gender: M,
    age: 23,
    interestedIn: [W],
    sports: [["parkour", 3], ["calisthenics", 2]],
    bio:
      "Parkour sur les toits de Confluence (avec autorisation, promis). Étudiant en ingénierie, je vois des obstacles partout.",
    goal: "Un saut de chat de quatre mètres",
    spot: "Le quartier de Confluence",
    lifestyle: ["Night owl", "Omnivore", "Never", "Never"],
    prompts: [[
      "My most irrational fear",
      "Les ascenseurs. Je prends les escaliers, en courant.",
    ], [
      "My hidden talent nobody believes",
      "Je fais un salto arrière depuis la position assise.",
    ]],
  },
  {
    name: "Lucie",
    gender: W,
    age: 33,
    interestedIn: [M],
    sports: [["cycling", 2], ["hiking", 2], ["yoga", 1]],
    bio:
      "Cheffe de projet dans l'humanitaire, cyclotouriste. J'ai traversé l'Europe à vélo et je cherche quelqu'un pour le prochain voyage.",
    goal: "Lyon-Istanbul à vélo",
    spot: "La ViaRhôna",
    lifestyle: ["Early bird", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "The piece of gear I'd save in a fire",
      "Mes sacoches, pleines de souvenirs.",
    ], [
      "Together we could finally",
      "Partir trois semaines avec une tente et deux vélos.",
    ]],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai traversé l'Europe à vélo",
        "J'ai dormi dans une église en Italie",
        "J'ai déjà crevé dix fois dans la même journée",
      ],
      lieIndex: 2,
    },
  },
  {
    name: "Benjamin",
    gender: M,
    age: 37,
    interestedIn: [W],
    sports: [["tennis", 2], ["squash", 2], ["running", 1]],
    bio: "Banquier, sportif de raquette. Le squash me sert à évacuer, le tennis à socialiser.",
    goal: "Battre enfin mon frère au squash",
    spot: "Le club de squash de la Part-Dieu",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My competitive streak, rated",
      "Suffisant pour ne pas parler à mon frère pendant une semaine.",
    ], ["After a workout you'll find me", "Au sauna, en silence."]],
  },
  {
    name: "Eva",
    gender: W,
    age: 28,
    interestedIn: [M],
    sports: [["crossfit", 3], ["running", 1]],
    bio:
      "CrossFit trois fois par semaine, infirmière au bloc. Je suis calme sous pression et pas sous une barre de 60 kg.",
    goal: "Mon premier muscle-up",
    spot: "La box de Vaise",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "The best advice a coach ever gave me",
      "La barre ne te jugera pas.",
    ], [
      "I'll know it's a match if",
      "Tu ne te moques pas de mes mains pleines de corne.",
    ]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Wall balls ou burpees ?",
      options: ["Wall balls", "Burpees"],
      pick: 0,
    },
  },
  {
    name: "Clément",
    gender: M,
    age: 31,
    interestedIn: [W],
    sports: [["trail", 2], ["running", 2], ["cycling", 1]],
    bio:
      "Ingénieur chez un fabricant de chaussures de trail, donc je teste. Beaucoup. Je connais les Monts d'Or par cœur.",
    goal: "L'UTMB d'ici trois ans",
    spot: "Le Mont Thou",
    lifestyle: ["Early bird", "Omnivore", "Post-race only", "Never"],
    prompts: [[
      "The piece of gear I'd save in a fire",
      "Mes chaussures de test. Elles valent de l'or.",
    ], [
      "My ideal Sunday session",
      "Le tour des Monts d'Or, 30 km, puis une sieste.",
    ]],
  },
  {
    name: "Ambre",
    gender: W,
    age: 24,
    interestedIn: [M, W],
    sports: [["volleyball", 2], ["running", 1], ["yoga", 1]],
    bio: "Volley en club, étudiante en droit. Je suis la première à proposer un apéro après le match.",
    goal: "Courir un semi cette année",
    spot: "Le parc de la Feyssine",
    lifestyle: ["Night owl", "Flexitarian", "Apéro is sacred", "Sometimes"],
    prompts: [["Karaoke song, no hesitation", "Bella, de Maître Gims."], [
      "My love language is basically",
      "Partager mes frites. C'est rare.",
    ]],
  },
  {
    name: "Quentin",
    gender: M,
    age: 29,
    interestedIn: [W],
    sports: [["spinning", 3], ["strength", 2]],
    bio: "Prof de spinning, ambiance boîte de nuit à 7h du mat. Je mets la musique fort, sur le vélo comme en voiture.",
    goal: "Ouvrir mon propre studio",
    spot: "Le studio de spinning du 2e",
    lifestyle: ["Very early bird", "Omnivore", "Socially", "Never"],
    prompts: [["My playlist for the last kilometre", "Daft Punk, toujours."], [
      "You should not go out with me if",
      "Tu détestes la musique forte.",
    ]],
    icebreaker: {
      kind: "joke",
      setup: "Pourquoi les vélos de spinning ne tombent jamais ?",
      punchline: "Parce qu'ils sont deux-tiers fatigués. Pardon.",
    },
  },
  {
    name: "Mathilde",
    gender: W,
    age: 36,
    interestedIn: [M],
    sports: [["swimming", 2], ["pilates", 2], ["walking", 2]],
    bio:
      "Journaliste, nageuse régulière, adepte du pilates pour mon dos de rédactrice. Je cherche quelqu'un de curieux.",
    goal: "La traversée de Lyon à la nage",
    spot: "Le centre nautique de Vénissieux",
    lifestyle: ["Early bird", "Pescatarian", "Socially", "Never"],
    prompts: [[
      "I'm looking for someone who",
      "Pose des questions et écoute les réponses.",
    ], [
      "Something I'm training for outside of sport",
      "Écrire mon premier livre.",
    ]],
  },
  {
    name: "Valentin",
    gender: M,
    age: 26,
    interestedIn: [W],
    sports: [["football", 3], ["running", 1]],
    bio:
      "Foot en club le dimanche, foot en salle le mercredi, foot à la télé le reste du temps. Électricien, je répare tout sauf mon genou.",
    goal: "Ne plus me blesser cette saison",
    spot: "Le stade de la Plaine des Jeux de Gerland",
    lifestyle: ["Night owl", "Meat lover", "Socially", "Never"],
    prompts: [[
      "I'd drop everything to watch",
      "Un match de l'OL, même en Ligue 2.",
    ], [
      "The dumbest injury I've ever had",
      "Ligaments croisés en célébrant un but.",
    ]],
  },
  {
    name: "Océane",
    gender: W,
    age: 27,
    interestedIn: [M],
    sports: [["paddleBoard", 2], ["swimming", 2], ["yoga", 1]],
    bio:
      "Paddle sur la Saône dès qu'il fait beau, yoga sur paddle quand je suis courageuse. Je travaille dans le tourisme.",
    goal: "Une descente du Rhône en paddle",
    spot: "La Saône, côté île Barbe",
    lifestyle: ["Early bird", "Pescatarian", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "Paddle au lever du soleil, puis brunch sur les quais.",
    ], [
      "My most irrational fear",
      "Tomber à l'eau devant tout le monde. C'est déjà arrivé.",
    ]],
    icebreaker: {
      kind: "guess",
      question: "Combien de fois je suis tombée à l'eau l'an dernier ?",
      options: ["Jamais", "3 fois", "Plus de 10"],
      answer: 2,
    },
  },
  {
    name: "Martin",
    gender: M,
    age: 34,
    interestedIn: [W],
    sports: [["hiking", 3], ["running", 1], ["skiing", 1]],
    bio: "Prof de SVT, randonneur passionné. Je connais le nom de chaque fleur sur le sentier, et je vais te les dire.",
    goal: "Le tour du Queyras",
    spot: "Le Mont Pilat",
    lifestyle: ["Early bird", "Vegetarian", "Rarely", "Never"],
    prompts: [[
      "A first date that isn't dinner",
      "Une rando avec pique-nique, je m'occupe du fromage.",
    ], ["I will never shut up about", "Les orchidées sauvages."]],
  },
  {
    name: "Pauline",
    gender: W,
    age: 29,
    interestedIn: [M],
    sports: [["running", 2], ["strength", 2], ["yoga", 1]],
    bio: "RH le jour, muscu le soir. J'ai découvert la musculation il y a deux ans et ça a tout changé.",
    goal: "Soulever une fois et demie mon poids au soulevé de terre",
    spot: "La salle de Brotteaux",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "Something I'm training for outside of sport",
      "Dire non sans me justifier.",
    ], ["Green flag in a training partner", "Il remet les poids en place."]],
  },
  {
    name: "Sacha",
    gender: N,
    age: 29,
    interestedIn: [],
    sports: [["bouldering", 2], ["running", 2]],
    bio:
      "UX designer, je cours sur les quais et je grimpe à Vertical'Art. Je fais aussi des céramiques ratées avec beaucoup d'amour.",
    goal: "Courir un 20 km sans pause",
    spot: "Vertical'Art Lyon",
    lifestyle: ["Night owl", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "My hidden talent nobody believes",
      "Je fabrique des tasses. Elles fuient un peu.",
    ], ["I'll know it's a match if", "Tu acceptes un mug bancal en cadeau."]],
    icebreaker: {
      kind: "hotTake",
      text: "Le bloc, c'est surtout du lien social avec un peu de grimpe.",
    },
  },
  {
    name: "Florian",
    gender: M,
    age: 33,
    interestedIn: [W],
    sports: [["triathlon", 3], ["running", 2]],
    bio:
      "Triathlète du dimanche devenu triathlète tous les jours. Commercial dans le vélo, ce qui n'aide pas mon budget.",
    goal: "Mon premier 70.3",
    spot: "Le lac des Sapins",
    lifestyle: ["Early bird", "Omnivore", "Post-race only", "Never"],
    prompts: [[
      "My pre-race ritual involves",
      "Toujours la même trifonction, lavée la veille.",
    ], [
      "Rest day? Here's what that really means",
      "Une sortie vélo tranquille. Tranquille.",
    ]],
  },
  {
    name: "Marie",
    gender: W,
    age: 38,
    interestedIn: [M],
    sports: [["running", 3], ["walking", 2]],
    bio:
      "Professeure des écoles, je cours pour mon équilibre. J'aime les gens simples, les dimanches calmes et les gâteaux maison.",
    goal: "Un 10 km en moins de 50 minutes",
    spot: "Le parc de la Tête d'Or",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "The way to win me over",
      "Un gâteau au chocolat. Fait maison, évidemment.",
    ], ["What keeps me going on hard days", "Le rire de mes élèves."]],
  },
  {
    name: "Tristan",
    gender: M,
    age: 28,
    interestedIn: [W],
    sports: [["snowboarding", 2], ["skateboarding", 2], ["surfing", 1]],
    bio:
      "Rider dans l'âme, snow l'hiver, skate et surf le reste de l'année. Je bosse dans un shop de glisse à la Presqu'île.",
    goal: "Une saison complète à Tignes",
    spot: "Le skatepark de la Croix-Rousse",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Sometimes"],
    prompts: [[
      "My ideal Sunday session",
      "Première benne à Tignes, dernière descente au coucher du soleil.",
    ], [
      "My most controversial opinion",
      "Le ski, c'est pour ceux qui ont peur de tomber.",
    ]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Poudreuse ou piste damée ?",
      options: ["Poudreuse", "Piste damée"],
      pick: 0,
    },
  },
  {
    name: "Laura",
    gender: W,
    age: 31,
    interestedIn: [M],
    sports: [["climbing", 2], ["trail", 2]],
    bio:
      "Ingénieure en aéronautique, grimpeuse et traileuse. J'aime les gens qui ont le vertige mais qui y vont quand même.",
    goal: "Grimper une grande voie dans les Calanques",
    spot: "Les falaises de Dent du Chat",
    lifestyle: ["Early bird", "Omnivore", "Rarely", "Never"],
    prompts: [[
      "A goal that scares me a little",
      "Une grande voie de 300 mètres.",
    ], ["I'm looking for someone who", "Me fait confiance pour l'assurer."]],
  },
  {
    name: "Kylian",
    gender: M,
    age: 22,
    interestedIn: [W],
    sports: [["basketball", 2], ["strength", 3]],
    bio:
      "Étudiant en STAPS, muscu et basket. Je veux devenir préparateur physique, donc oui, je vais corriger ta posture.",
    goal: "Mon diplôme et 1 m de détente verticale",
    spot: "Le playground de la Croix-Rousse",
    lifestyle: ["Night owl", "Meat lover", "Never", "Never"],
    prompts: [[
      "Unpopular opinion about stretching",
      "Si, c'est important. Faites-le.",
    ], [
      "Two truths and a lie about my fitness",
      "Je dunke, je fais 20 tractions, je suis souple.",
    ]],
  },
  {
    name: "Céline",
    gender: W,
    age: 41,
    interestedIn: [M],
    sports: [["yoga", 3], ["hiking", 2]],
    bio:
      "Directrice artistique, deux grands enfants, une nouvelle passion pour la randonnée. Je cherche quelqu'un de doux et de drôle.",
    goal: "Le chemin de Stevenson",
    spot: "Les crêtes du Mont d'Or",
    lifestyle: ["Early bird", "Flexitarian", "Socially", "Never"],
    prompts: [[
      "I feel most like myself when",
      "Je marche sans destination précise.",
    ], ["The way to win me over", "Me faire rire au moins une fois par jour."]],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai vécu deux ans à Montréal",
        "J'ai fait le tour de la Corse à pied",
        "Je ne sais pas nager",
      ],
      lieIndex: 1,
    },
  },
  {
    name: "Guillaume",
    gender: M,
    age: 39,
    interestedIn: [W],
    sports: [["cycling", 3], ["running", 1], ["swimming", 1]],
    bio: "Fonctionnaire, cycliste chevronné, cuisinier du dimanche. Je fais une excellente quiche lorraine.",
    goal: "Les 7 Majeurs en une journée",
    spot: "Le col du Grand Bois",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "After a workout you'll find me",
      "En cuisine, à préparer une quiche.",
    ], [
      "Green flag in a training partner",
      "Il partage ses barres de céréales.",
    ]],
  },
  {
    name: "Anaïs",
    gender: W,
    age: 26,
    interestedIn: [M],
    sports: [["boxing", 2], ["running", 2]],
    bio: "Boxe le mardi, course le jeudi, apéro le vendredi. Je bosse dans une startup et je parle trop vite.",
    goal: "Mon premier gala de boxe",
    spot: "La salle de boxe de Vaise",
    lifestyle: ["Night owl", "Omnivore", "Apéro is sacred", "Never"],
    prompts: [[
      "My competitive streak, rated",
      "Je compte les pas des autres sur leur montre.",
    ], [
      "A first date that isn't dinner",
      "Une séance de boxe, puis un burger.",
    ]],
  },
  {
    name: "Bastien",
    gender: M,
    age: 30,
    interestedIn: [W],
    sports: [["volleyball", 2], ["beachVolley", 1], ["running", 1]],
    bio: "Volleyeur, comptable, amateur de jeux de société. Je gagne aux Colons de Catane, rarement au volley.",
    goal: "Le tournoi de beach de Miribel",
    spot: "Le gymnase de Gerland",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Never"],
    prompts: [[
      "Together we could finally",
      "Gagner un tournoi. De jeux de société ou de volley.",
    ], ["My most controversial opinion", "Le Monopoly est un mauvais jeu."]],
    icebreaker: {
      kind: "guess",
      question: "Combien de jeux de société j'ai ?",
      options: ["15", "40", "Plus de 80"],
      answer: 2,
    },
  },
  {
    name: "Laurine",
    gender: W,
    age: 29,
    interestedIn: [M],
    sports: [["badminton", 3], ["running", 1]],
    bio: "Badminton en compétition, pharmacienne. Je smashe fort et je conseille bien sur les anti-inflammatoires.",
    goal: "Le championnat régional en double mixte",
    spot: "Le gymnase du 8e",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [["Green flag in a training partner", "Il ramasse les volants."], [
      "I'm looking for someone who",
      "N'a pas peur du double mixte.",
    ]],
  },
  {
    name: "Simon",
    gender: M,
    age: 32,
    interestedIn: [M],
    sports: [["running", 3], ["swimming", 1], ["yoga", 1]],
    bio:
      "Je cours au lever du soleil, je nage le midi, je fais du yoga le soir. Infographiste, je collectionne les plantes.",
    goal: "Le marathon de Berlin",
    spot: "Les quais de Saône",
    lifestyle: ["Very early bird", "Vegetarian", "Rarely", "Never"],
    prompts: [[
      "I will never shut up about",
      "Mes 43 plantes. Elles ont toutes un nom.",
    ], ["My ideal Sunday session", "Une sortie longue et un marché bio."]],
  },
  {
    name: "Héloïse",
    gender: W,
    age: 34,
    interestedIn: [M],
    sports: [["fencing", 2], ["running", 2]],
    bio: "Escrimeuse depuis l'enfance, sabre uniquement. Avocate, donc le combat, je connais.",
    goal: "Les championnats de France vétérans",
    spot: "La salle d'armes de Lyon",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [["My competitive streak, rated", "Touché. Toujours."], [
      "You should not go out with me if",
      "Tu as peur des débats animés.",
    ]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Sabre ou fleuret ?",
      options: ["Sabre", "Fleuret"],
      pick: 0,
    },
  },
  {
    name: "Axel",
    gender: M,
    age: 27,
    interestedIn: [W],
    sports: [["mountainBiking", 3], ["trail", 1]],
    bio: "VTT enduro, mécanicien vélo. Je répare ton vélo, mais pas ton cœur. Enfin, on peut essayer.",
    goal: "La Mégavalanche",
    spot: "Le bike park de Saint-Genis-Laval",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Sometimes"],
    prompts: [[
      "The dumbest injury I've ever had",
      "Doigt pincé dans un dérailleur. En boutique.",
    ], ["The piece of gear I'd save in a fire", "Ma fourche suspendue."]],
  },
  {
    name: "Justine",
    gender: W,
    age: 25,
    interestedIn: [M],
    sports: [["running", 2], ["dance", 2]],
    bio:
      "Je suis passée de la danse classique à la course à pied, sans transition. Étudiante en médecine, toujours en manque de sommeil.",
    goal: "Le semi de Lyon",
    spot: "Le parc de Gerland",
    lifestyle: ["Night owl", "Flexitarian", "Rarely", "Never"],
    prompts: [[
      "What keeps me going on hard days",
      "Le café. Beaucoup de café.",
    ], [
      "Something I'm training for outside of sport",
      "L'internat. Souhaite-moi bonne chance.",
    ]],
  },
  {
    name: "Dylan",
    gender: M,
    age: 29,
    interestedIn: [W],
    sports: [["boxing", 2], ["strength", 2], ["running", 1]],
    bio: "Pompier volontaire, boxeur, cuisinier correct. Je suis du genre à porter les courses de toute la rue.",
    goal: "Le concours de pompier professionnel",
    spot: "La caserne, et le parc de Parilly",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "Green flag in a training partner",
      "Il donne tout, même quand personne ne regarde.",
    ], [
      "My love language is basically",
      "Te porter quand tu as mal aux pieds.",
    ]],
    icebreaker: {
      kind: "joke",
      setup: "Pourquoi les pompiers sont de bons partenaires ?",
      punchline: "Parce qu'ils savent gérer les situations brûlantes.",
    },
  },
  {
    name: "Noémie",
    gender: W,
    age: 32,
    interestedIn: [M],
    sports: [["trail", 2], ["yoga", 2]],
    bio:
      "Prof de français, traileuse tranquille, je m'arrête pour prendre des photos. Je préfère les beaux sentiers aux chronos.",
    goal: "Le trail des Hospitaliers",
    spot: "Les sentiers du Pilat",
    lifestyle: ["Early bird", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "Un sentier, un thermos, aucune montre.",
    ], [
      "I'll know it's a match if",
      "Tu t'arrêtes avec moi pour regarder la vue.",
    ]],
  },
  {
    name: "Yanis",
    gender: M,
    age: 24,
    interestedIn: [W],
    sports: [["football", 2], ["running", 2]],
    bio: "Commis de cuisine dans un bouchon du Vieux Lyon. Je cours pour compenser le gratin dauphinois.",
    goal: "Devenir chef et finir un marathon",
    spot: "Le Vieux Lyon, à l'aube",
    lifestyle: ["Night owl", "Meat lover", "Socially", "Never"],
    prompts: [[
      "The snack that fuels my entire personality",
      "Une praline rose, directement du sachet.",
    ], [
      "A first date that isn't dinner",
      "Une course sur les quais, je cuisine après.",
    ]],
  },
  {
    name: "Elsa",
    gender: W,
    age: 30,
    interestedIn: [M, W],
    sports: [["swimming", 2], ["cycling", 2], ["running", 1]],
    bio: "Biologiste marine perdue à Lyon. Je nage à la piscine en rêvant de l'océan, je pédale pour oublier.",
    goal: "Mon premier triathlon",
    spot: "La piscine de Vaise",
    lifestyle: ["Early bird", "Pescatarian", "Socially", "Never"],
    prompts: [[
      "I will never shut up about",
      "Les pieuvres. Elles ont trois cœurs, tu savais ?",
    ], ["Together we could finally", "Partir plonger en Bretagne."]],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai nagé avec des requins",
        "J'ai peur du noir",
        "J'ai déjà vécu sur un bateau",
      ],
      lieIndex: 1,
    },
  },
  {
    name: "Thibault",
    gender: M,
    age: 35,
    interestedIn: [W],
    sports: [["skiing", 2], ["crossCountrySki", 1], ["running", 2]],
    bio: "Moniteur de ski l'hiver, guide de rando l'été, à Lyon entre les saisons. Je m'adapte à toutes les météos.",
    goal: "La Transjurassienne",
    spot: "Les Rousses en hiver",
    lifestyle: ["Very early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "Ski de fond au lever du soleil, puis fondue.",
    ], ["The best advice a coach ever gave me", "Plie les genoux. Pour tout."]],
  },
  {
    name: "Capucine",
    gender: W,
    age: 28,
    interestedIn: [M],
    sports: [["hiking", 2], ["running", 2], ["yoga", 1]],
    bio: "Fleuriste, randonneuse, coureuse du dimanche. Je ramène toujours un bouquet de mes randos.",
    goal: "Le GR5 de Genève à Nice",
    spot: "Les prairies du Mont Pilat",
    lifestyle: ["Early bird", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "My hidden talent nobody believes",
      "Je reconnais une fleur à l'odeur.",
    ], [
      "The way to win me over",
      "Une randonnée qui finit par un pique-nique.",
    ]],
  },
  {
    name: "Nicolas",
    gender: M,
    age: 42,
    interestedIn: [W],
    sports: [["running", 2], ["tennis", 2], ["golf", 1]],
    bio:
      "Dentiste, sportif polyvalent, papa d'une ado. Je cours, je joue au tennis, je découvre le golf. Je souris beaucoup, déformation professionnelle.",
    goal: "Le semi de Lyon avec ma fille",
    spot: "Le parc de la Tête d'Or",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "After a workout you'll find me",
      "Au marché de la Croix-Rousse.",
    ], [
      "I'm looking for someone who",
      "Aime les dimanches tranquilles et les rires francs.",
    ]],
  },
  {
    name: "Maëlle",
    gender: W,
    age: 24,
    interestedIn: [M],
    sports: [["climbing", 2], ["bouldering", 2]],
    bio:
      "Étudiante en géographie, grimpeuse acharnée. Je vis dans un petit appart avec une poutre d'entraînement au-dessus de la porte.",
    goal: "Le 6c en tête",
    spot: "La salle Azium",
    lifestyle: ["Night owl", "Vegetarian", "Rarely", "Never"],
    prompts: [[
      "A stat I'm weirdly proud of",
      "Suspendue 40 secondes à la poutre.",
    ], [
      "I'll know it's a match if",
      "Tu m'assures sans regarder ton téléphone.",
    ]],
  },
  {
    name: "Loïc",
    gender: M,
    age: 31,
    interestedIn: [W],
    sports: [["swimming", 3], ["openWater", 1], ["triathlon", 1]],
    bio: "Maître-nageur, nageur en eau libre. Je connais les lacs de la région mieux que mon quartier.",
    goal: "La traversée du lac Léman",
    spot: "Le lac d'Aiguebelette",
    lifestyle: ["Very early bird", "Omnivore", "Rarely", "Never"],
    prompts: [[
      "My most irrational fear",
      "Les algues qui frôlent les pieds. Oui, moi.",
    ], ["The best advice a coach ever gave me", "Glisse, ne force pas."]],
    icebreaker: {
      kind: "guess",
      question: "Ma plus longue nage en eau libre ?",
      options: ["5 km", "10 km", "15 km"],
      answer: 1,
    },
  },
  {
    name: "Coralie",
    gender: W,
    age: 35,
    interestedIn: [M],
    sports: [["barre", 2], ["running", 2], ["pilates", 1]],
    bio: "Danseuse reconvertie en prof de barre au sol. J'aime les gens qui tiennent leurs promesses et leur gainage.",
    goal: "Courir le marathon de New York",
    spot: "Mon studio à Monplaisir",
    lifestyle: ["Early bird", "Flexitarian", "Socially", "Never"],
    prompts: [[
      "Green flag in a training partner",
      "Il ne compte pas à voix haute.",
    ], [
      "You should not go out with me if",
      "Tu n'aimes pas danser en cuisine.",
    ]],
  },
  {
    name: "Sébastien",
    gender: M,
    age: 44,
    interestedIn: [W],
    sports: [["cycling", 3], ["hiking", 1]],
    bio:
      "Ingénieur, cycliste sur route depuis trente ans. Je connais chaque col autour de Lyon. Calme, fidèle, un peu têtu.",
    goal: "Paris-Brest-Paris",
    spot: "Le col de la Luère",
    lifestyle: ["Very early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "A stat I'm weirdly proud of",
      "250 000 km au compteur depuis mes 14 ans.",
    ], [
      "My ideal Sunday session",
      "Six heures de vélo et une sieste au soleil.",
    ]],
  },
  {
    name: "Oriane",
    gender: W,
    age: 27,
    interestedIn: [M],
    sports: [["padel", 2], ["running", 1], ["strength", 1]],
    bio: "Chargée de com, padel le midi avec les collègues. Je cherche un partenaire qui ne gueule pas quand je rate.",
    goal: "Ne plus rater les balles basses",
    spot: "Le padel de Gerland",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Never"],
    prompts: [[
      "The way to win me over",
      "Me laisser gagner un set. Discrètement.",
    ], ["Karaoke song, no hesitation", "Toxic, de Britney Spears."]],
    icebreaker: {
      kind: "hotTake",
      text: "La vitre du padel est le meilleur partenaire.",
    },
  },
  {
    name: "Rémi",
    gender: M,
    age: 29,
    interestedIn: [W],
    sports: [["trail", 2], ["climbing", 1], ["running", 2]],
    bio: "Paysagiste, coureur des bois. Je passe ma vie dehors et je ne vois pas pourquoi ça changerait.",
    goal: "La Maxi-Race d'Annecy",
    spot: "Le bois de Serres",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "I feel most like myself when",
      "Je suis couvert de boue en haut d'une côte.",
    ], ["Together we could finally", "Courir dans la forêt sans se perdre."]],
  },
  {
    name: "Andréa",
    gender: N,
    age: 31,
    interestedIn: [],
    sports: [["running", 2], ["dance", 2], ["yoga", 1]],
    bio: "Je joue au théâtre, je cours sur les quais, je danse en soirée. Je change de rôle mais pas d'énergie.",
    goal: "Courir pendant toute une représentation de Hamlet",
    spot: "Les pentes de la Croix-Rousse",
    lifestyle: ["Night owl", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "I feel most like myself when",
      "Je suis sur scène ou en train de courir sur les quais.",
    ], ["Karaoke song, no hesitation", "Formidable, de Stromae."]],
  },
  {
    name: "Mathieu",
    gender: M,
    age: 33,
    interestedIn: [W],
    sports: [["tableTennis", 2], ["running", 2]],
    bio: "Ping-pong en club, course le week-end. Ingénieur son, donc je parle fort et j'écoute bien.",
    goal: "Classé 15 en tennis de table",
    spot: "Le club de ping de Villeurbanne",
    lifestyle: ["Night owl", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My hidden talent nobody believes",
      "Je rattrape une balle de ping avec une baguette.",
    ], ["My competitive streak, rated", "Je ne joue jamais pour le plaisir."]],
    icebreaker: {
      kind: "thisOrThat",
      question: "Coup droit ou revers ?",
      options: ["Coup droit", "Revers"],
      pick: 1,
    },
  },
  {
    name: "Clémence",
    gender: W,
    age: 30,
    interestedIn: [M],
    sports: [["running", 3], ["obstacleRace", 1]],
    bio:
      "Chargée d'affaires, coureuse, et j'adore les courses à obstacles pleines de boue. Je ne crains ni le froid ni la honte.",
    goal: "Une Spartan Beast",
    spot: "Le parc de Parilly",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "The worst run of my life happened when",
      "J'ai perdu une chaussure dans la boue au km 3.",
    ], [
      "Green flag in a training partner",
      "Il te tend la main au-dessus du mur.",
    ]],
  },
  {
    name: "Yann",
    gender: M,
    age: 36,
    interestedIn: [W],
    sports: [["sailing", 2], ["running", 2], ["swimming", 1]],
    bio: "Breton exilé à Lyon, voileux, coureur. Je cherche quelqu'un pour naviguer l'été et courir l'hiver.",
    goal: "La Route du Rhum, un jour",
    spot: "Le lac de Monteynard",
    lifestyle: ["Early bird", "Pescatarian", "Socially", "Never"],
    prompts: [
      ["I will never shut up about", "La Bretagne. Et le beurre salé."],
      ["A first date that isn't dinner", "Une journée en voilier sur un lac."],
    ],
  },
  {
    name: "Lisa",
    gender: W,
    age: 23,
    interestedIn: [M],
    sports: [["gymnastics", 2], ["yoga", 2]],
    bio: "Ancienne gymnaste, étudiante en kiné. Je fais encore des roues dans la rue, désolée pour les passants.",
    goal: "Retrouver mon salto arrière",
    spot: "Le gymnase de la Doua",
    lifestyle: ["Early bird", "Flexitarian", "Rarely", "Never"],
    prompts: [[
      "My hidden talent nobody believes",
      "Je fais le grand écart sur une chaise.",
    ], [
      "Unpopular opinion about stretching",
      "C'est le meilleur moment de la séance.",
    ]],
  },
  {
    name: "François",
    gender: M,
    age: 43,
    interestedIn: [W],
    sports: [["hiking", 2], ["cycling", 2]],
    bio:
      "Vigneron dans le Beaujolais, randonneur et cycliste. J'aime le travail bien fait, les bons vins et les gens sincères.",
    goal: "Le GR65 jusqu'à Conques",
    spot: "Les coteaux du Beaujolais",
    lifestyle: ["Early bird", "Omnivore", "Apéro is sacred", "Never"],
    prompts: [[
      "After a workout you'll find me",
      "À la cave, à goûter le millésime.",
    ], [
      "I'm looking for someone who",
      "Aime la campagne autant que la ville.",
    ]],
  },
  {
    name: "Aurélie",
    gender: W,
    age: 39,
    interestedIn: [M],
    sports: [["running", 2], ["swimming", 2], ["pilates", 1]],
    bio: "Cheffe de service à l'hôpital, maman solo. Le sport est mon moment à moi, et j'y tiens.",
    goal: "Un triathlon S avec mes collègues",
    spot: "Les quais du Rhône",
    lifestyle: ["Early bird", "Flexitarian", "Socially", "Never"],
    prompts: [[
      "What keeps me going on hard days",
      "Mon heure de piscine, rien qu'à moi.",
    ], ["The way to win me over", "Prendre des nouvelles sans attendre."]],
  },
  {
    name: "Enzo",
    gender: M,
    age: 26,
    interestedIn: [W],
    sports: [["martialArts", 2], ["running", 1], ["calisthenics", 2]],
    bio: "Judo depuis l'âge de 5 ans, développeur jeux vidéo. Je te mets au sol en deux secondes, mais avec respect.",
    goal: "Ceinture noire 2e dan",
    spot: "Le dojo du 3e",
    lifestyle: ["Night owl", "Omnivore", "Never", "Never"],
    prompts: [[
      "The best advice a coach ever gave me",
      "Tomber, c'est apprendre.",
    ], ["I'd drop everything to watch", "Les finales de judo aux JO."]],
  },
  {
    name: "Sophie",
    gender: W,
    age: 33,
    interestedIn: [M],
    sports: [["hyrox", 2], ["running", 2], ["strength", 1]],
    bio:
      "Consultante, accro à Hyrox depuis un an. Je cherche un partenaire pour le double mixte, et peut-être pour la vie.",
    goal: "Hyrox Pro en moins de 1h20",
    spot: "La salle Hyrox de Vaise",
    lifestyle: ["Early bird", "Omnivore", "Rarely", "Never"],
    prompts: [
      ["Together we could finally", "Faire un Hyrox en double mixte."],
      [
        "A stat I'm weirdly proud of",
        "Le sled push le plus rapide de ma salle.",
      ],
    ],
    icebreaker: {
      kind: "twoTruths",
      statements: [
        "J'ai fait trois Hyrox cette année",
        "Je déteste les burpees",
        "J'ai déjà vomi après un wall ball",
      ],
      lieIndex: 1,
    },
  },
  {
    name: "Benoît",
    gender: M,
    age: 37,
    interestedIn: [W],
    sports: [["running", 2], ["walking", 2], ["yoga", 1]],
    bio: "Libraire, coureur lent, marcheur rapide. J'ai toujours un livre dans mon sac de sport.",
    goal: "Courir 1 000 km cette année",
    spot: "Le parc des Hauteurs",
    lifestyle: ["Early bird", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "My love language is basically",
      "Te prêter un livre et attendre ton avis.",
    ], [
      "My ideal Sunday session",
      "Une sortie lente, puis trois heures de lecture.",
    ]],
  },
  {
    name: "Marine",
    gender: W,
    age: 28,
    interestedIn: [M],
    sports: [["surfing", 1], ["yoga", 2], ["swimming", 1]],
    bio: "Je rêve de la mer depuis Lyon. Yoga et piscine la semaine, surf dès que je peux filer sur la côte.",
    goal: "Une saison au Portugal",
    spot: "La piscine du Rhône",
    lifestyle: ["Early bird", "Vegetarian", "Socially", "Never"],
    prompts: [[
      "My most irrational fear",
      "Les vagues de plus de deux mètres. Pour l'instant.",
    ], ["Together we could finally", "Partir en van jusqu'à Biarritz."]],
  },
  {
    name: "Kevin",
    gender: M,
    age: 30,
    interestedIn: [W],
    sports: [["hockey", 2], ["strength", 2]],
    bio:
      "Hockey sur glace avec les Lions de Lyon amateurs, technicien informatique. Sur la glace je fonce, dans la vie je suis plutôt doux.",
    goal: "Le tournoi national amateur",
    spot: "La patinoire Charlemagne",
    lifestyle: ["Night owl", "Meat lover", "Socially", "Never"],
    prompts: [[
      "The dumbest injury I've ever had",
      "Une dent en moins, en patinant pour le plaisir.",
    ], [
      "A first date that isn't dinner",
      "Une séance de patinoire, je te tiens la main.",
    ]],
    icebreaker: {
      kind: "joke",
      setup: "Pourquoi les joueurs de hockey ont toujours froid ?",
      punchline: "Parce qu'ils jouent sur la glace. Je n'ai pas mieux.",
    },
  },
  {
    name: "Pauline",
    gender: W,
    age: 34,
    interestedIn: [M],
    sports: [["mountainBiking", 2], ["trail", 1], ["skiing", 1]],
    bio:
      "Prof de sport au collège, VTT, ski et trail. J'aime les descentes rapides et les gens qui ne freinent pas trop.",
    goal: "Une descente de la Mégavalanche",
    spot: "Les singles du Mont Verdun",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "The dumbest injury I've ever had",
      "Une côte fêlée en tombant de mon vélo. À l'arrêt.",
    ], [
      "Green flag in a training partner",
      "Il attend en haut de la côte sans soupirer.",
    ]],
  },
  {
    name: "Adrien",
    gender: M,
    age: 28,
    interestedIn: [W],
    sports: [["running", 3], ["cycling", 1]],
    bio:
      "Chercheur en neurosciences, coureur. Je peux t'expliquer pourquoi tu aimes courir, mais je préfère courir avec toi.",
    goal: "Le marathon de Lyon en 3h",
    spot: "Les berges du Rhône",
    lifestyle: ["Early bird", "Omnivore", "Rarely", "Never"],
    prompts: [["A stat I'm weirdly proud of", "Un 10 km en 36 minutes."], [
      "I'm looking for someone who",
      "Pose des questions bizarres à 22h.",
    ]],
  },
  {
    name: "Léna",
    gender: W,
    age: 26,
    interestedIn: [M, W, N],
    sports: [["skateboarding", 2], ["dance", 1], ["running", 1]],
    bio: "Graphiste, skateuse, danseuse de soirée. Je suis tombée cent fois, je suis toujours là.",
    goal: "Un ollie sur une marche",
    spot: "Les quais de Saône, côté Saint-Paul",
    lifestyle: ["Night owl", "Vegan", "Socially", "Sometimes"],
    prompts: [[
      "The dumbest injury I've ever had",
      "Un poignet cassé en filmant une figure, pas en la faisant.",
    ], [
      "You should not go out with me if",
      "Tu n'aimes pas les concerts debout.",
    ]],
  },
  {
    name: "Arnaud",
    gender: M,
    age: 41,
    interestedIn: [W],
    sports: [["swimming", 2], ["cycling", 2], ["running", 1]],
    bio: "Pharmacien, triathlète du week-end, papa de jumeaux. Je fais tout en double, sauf les sorties vélo.",
    goal: "Le triathlon d'Embrun",
    spot: "Le lac de Miribel",
    lifestyle: ["Very early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "Rest day? Here's what that really means",
      "Courir après mes jumeaux au parc.",
    ], [
      "The way to win me over",
      "Me laisser dormir le dimanche matin. Une fois.",
    ]],
  },
  {
    name: "Victoria",
    gender: W,
    age: 29,
    interestedIn: [M],
    sports: [["tennis", 2], ["pilates", 1], ["running", 1]],
    bio: "Chargée d'affaires, joueuse de tennis classée. Je cherche quelqu'un qui accepte de perdre avec élégance.",
    goal: "Passer 15",
    spot: "Le Lyon Tennis Club",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My competitive streak, rated",
      "Je joue chaque point comme une balle de match.",
    ], [
      "After a workout you'll find me",
      "Au café du club, à refaire le match.",
    ]],
  },
  {
    name: "Malik",
    gender: M,
    age: 31,
    interestedIn: [W],
    sports: [["bjj", 3], ["strength", 1], ["running", 1]],
    bio: "Jiu-jitsu brésilien, infirmier en psychiatrie. Je suis très calme, sauf quand on me met en garde fermée.",
    goal: "Ceinture violette",
    spot: "L'académie de JJB de Villeurbanne",
    lifestyle: ["Early bird", "Omnivore", "Never", "Never"],
    prompts: [[
      "The best advice a coach ever gave me",
      "Sois à l'aise dans l'inconfort.",
    ], ["Green flag in a training partner", "Il tape avant de se blesser."]],
    icebreaker: {
      kind: "hotTake",
      text: "Le jiu-jitsu, c'est des échecs avec le corps.",
    },
  },
  {
    name: "Bérénice",
    gender: W,
    age: 36,
    interestedIn: [M],
    sports: [["walking", 2], ["hiking", 2], ["yoga", 1]],
    bio: "Archiviste, randonneuse, amoureuse des vieux villages. Je propose toujours un détour pour voir une chapelle.",
    goal: "Le chemin de Compostelle depuis Le Puy",
    spot: "Les villages des Monts d'Or",
    lifestyle: ["Early bird", "Flexitarian", "Rarely", "Never"],
    prompts: [[
      "A first date that isn't dinner",
      "Une balade dans le Vieux Lyon avec ses traboules.",
    ], ["I will never shut up about", "L'histoire des traboules."]],
  },
  {
    name: "Gaspard",
    gender: M,
    age: 25,
    interestedIn: [W],
    sports: [["rowing", 3], ["running", 1], ["strength", 1]],
    bio: "Rameur en club, étudiant en école d'ingé. Je me lève à 5h30, et je suis de bonne humeur. Désolé.",
    goal: "Les championnats de France universitaires",
    spot: "Le club d'aviron de Lyon",
    lifestyle: ["Very early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "Huit de pointe sur la Saône, puis un énorme petit déj.",
    ], [
      "You should not go out with me if",
      "Tu détestes les levers de soleil.",
    ]],
  },
  {
    name: "Romane",
    gender: W,
    age: 27,
    interestedIn: [M],
    sports: [["running", 2], ["hiit", 1], ["yoga", 1]],
    bio:
      "Sage-femme, coureuse débutante, fan de podcasts. Je cours en écoutant des enquêtes criminelles, rassurant non ?",
    goal: "Mon premier 10 km",
    spot: "Le parc de la Tête d'Or",
    lifestyle: ["Night owl", "Flexitarian", "Socially", "Never"],
    prompts: [[
      "My playlist for the last kilometre",
      "Un podcast de faits divers. Ça motive.",
    ], [
      "Together we could finally",
      "Finir une course ensemble, main dans la main.",
    ]],
  },
  {
    name: "Olivier",
    gender: M,
    age: 45,
    interestedIn: [W],
    sports: [["golf", 2], ["walking", 2], ["swimming", 1]],
    bio: "Notaire, golfeur, marcheur. Je cherche une compagne pour les balades du dimanche et les voyages hors saison.",
    goal: "Jouer un parcours en Écosse",
    spot: "Le golf de Salvagny",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "I feel most like myself when",
      "Je marche sur un parcours de golf au petit matin.",
    ], ["The way to win me over", "Un bon livre et une conversation sincère."]],
  },
  {
    name: "Inès",
    gender: W,
    age: 31,
    interestedIn: [M],
    sports: [["climbing", 2], ["running", 1], ["yoga", 1]],
    bio:
      "Architecte d'intérieur, grimpeuse du jeudi soir. J'ai un faible pour les jolies salles d'escalade et les bons cafés.",
    goal: "Ma première grande voie",
    spot: "La salle Block'Out",
    lifestyle: ["Early bird", "Flexitarian", "Socially", "Never"],
    prompts: [[
      "Green flag in a training partner",
      "Il m'encourage sans me donner la méthode.",
    ], [
      "A first date that isn't dinner",
      "Une séance d'escalade, puis un café de spécialité.",
    ]],
  },
  {
    name: "Hadrien",
    gender: M,
    age: 30,
    interestedIn: [W],
    sports: [["gravel", 2], ["trail", 1], ["cycling", 1]],
    bio:
      "Cartographe, je trace des itinéraires gravel autour de Lyon pour le plaisir. Je connais tous les chemins secrets du Lyonnais.",
    goal: "La Badlands en Andalousie",
    spot: "Les chemins des Monts du Lyonnais",
    lifestyle: ["Early bird", "Omnivore", "Socially", "Never"],
    prompts: [[
      "My ideal Sunday session",
      "120 km de gravel, zéro voiture, un bon sandwich.",
    ], ["I will never shut up about", "Les cartes IGN au 1:25 000."]],
  },
];
